<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PropertyCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            'Biztonság és vezetéstámogatás' => [
                'ABS (blokkolásgátló)',
                'ASR (kipörgésgátló)',
                'ESP (menetstabilizátor)',
                'EBD/EBV (elektronikus fékerő-elosztó)',
                'EDS (elektronikus differenciálzár)',
                'MSR (motorféknyomaték szabályzás)',
                'ARD (automatikus távolságtartó)',
                'Bekanyarodási asszisztens',
                'Éjjellátó asszisztens',
                'Fáradtságérzékelő',
                'Fékasszisztens',
                'Guminyomás-ellenőrző rendszer',
                'Holttér-figyelő rendszer',
                'Koccanásgátló',
                'Lejtmenet asszisztens',
                'Parkolóasszisztens',
                'Radaros fékasszisztens',
                'Sávtartó rendszer',
                'Sávváltó asszisztens',
                'Tábla-felismerő funkció',
                'Távolságtartó tempomat',
                'Ütközés veszélyre felkészítő rendszer',
                'Ütközésveszélyre figyelmeztető rendszer',
                'Vészfékasszisztens',
                'Visszagurulás-gátló',
                'Önvezető funkció',
                'Hátsó keresztirányú forgalomra figyelmeztetés',
            ],
            'Légzsákok és biztonság' => [
                'Függönylégzsák',
                'Gyalogos légzsák',
                'Hátsó oldal légzsák',
                'Kikapcsolható légzsák',
                'Középső légzsák elöl',
                'Oldallégzsák',
                'Térdlégzsák',
                'Utasoldali légzsák',
                'Vezetőoldali légzsák',
                'Indításgátló (immobiliser)',
                'Rablásgátló',
                'Riasztó',
                'Sebességváltó zár',
            ],
            'Kényelem és utastér' => [
                'Alcantara kárpit',
                'Állítható combtámasz',
                'Állítható hátsó ülések',
                'Állítható kormány',
                'Ajtószervó',
                'Beépített gyerekülés',
                'Bőr-szövet huzat',
                'Bőrbelső',
                'Bőrkormány',
                'Bőrülés',
                'Deréktámasz',
                'Dönthető utasülések',
                'Elektromosan állítható fejtámlák',
                'Hátsó fejtámlák',
                'Hűthető kartámasz',
                'Hűthető kesztyűtartó',
                'Kagylóülések',
                'Középső kartámasz',
                'Masszírozós ülés',
                'Memóriás utasülés',
                'Memóriás vezetőülés',
                'Műbőr-kárpit',
                'Plüss kárpit',
                'Sportülések',
                'Távirányítással ledönthető hátsó üléstámla',
                'Ülésmagasság-állítás',
                'Velúr kárpit',
            ],
            'Klímatizálás és fűtés' => [
                'Állófűtés',
                'Állóhelyzeti klíma',
                'Füthető ablakmosó fúvókák',
                'Füthető első és hátsó ülések',
                'Füthető első ülés',
                'Füthető kormány',
                'Füthető tükör',
                'Füthető ülések',
                'Fűtőszálas szélvédő',
                'Klíma elöl',
                'Klíma hátul',
                'Kétzónás klíma',
                'Légkondicionáló',
                'Üléshűtés',
                'Üléshűtés/Szellőztetés',
            ],
            'Infotainment és multimédia' => [
                '1 DIN',
                '2 DIN',
                'Analóg TV tuner',
                'Android Auto',
                'Apple CarPlay',
                'Autótelefon',
                'AUX csatlakozó',
                'Bluetooth',
                'Bluetooth-os kihangosító',
                'CD lejátszó',
                'CD Tár',
                'CD-s Autórádió',
                'Digitális műszeregység',
                'DVB tuner',
                'DVB-T tuner',
                'DVD',
                'Érintőkijelző',
                'Erősítő',
                'Erősítő kimenet',
                'Fejtámlamonitor',
                'FM Transzmitter',
                'GPS (navigáció)',
                'GPS nyomkövető',
                'Gyári erősítő',
                'Hangvezérlés',
                'HDMI Bemenet',
                'Hi-Fi',
                'iPhone/iPod Csatlakozó',
                'Kihangosító',
                'Kormányra szerelhető távirányító',
                'Kormányról vezérelhető hifi',
                'Memóriakártya-olvasó',
                'Mélynyomó',
                'Merevlemez',
                'Mikrofon bemenet',
                'MP3 Lejátszás',
                'MP4 Lejátszás',
                'Multifunkcionális kijelző',
                'Navigáció',
                'Rádió',
                'Rádiós magnó',
                'Tetőmonitor',
                'TV',
                'USB Csatlakozó',
                'Vezeték nélküli telefontöltés',
                'WiFi Hotspot',
                'WMA Lejátszás',
            ],
            'Hifirendszer és hangszórók' => [
                '2 Hangszóró',
                '4 Hangszóró',
                '5 Hangszóró',
                '6 Hangszóró',
                '7 Hangszóró',
                '8 Hangszóró',
                '9 Hangszóró',
                '10 Hangszóró',
                '11 Hangszóró',
                '12 Hangszóró',
            ],
            'Világítás és láthatóság' => [
                'Automata fényszórókapcsolás',
                'Automata távfény',
                'Automatikus távfény',
                'Bekanyarodási segédfény',
                'Bi-xenon fényszóró',
                'Esőszenzor',
                'Fényszóró magasságállítás',
                'Fényszórómosó',
                'Kanyarkövető fényszóró',
                'Kiegészítő fényszóró',
                'Ködlámpa',
                'LED fényszórók',
                'LED Mátrix fényszóró',
                'Menetfény',
                'Távolsági fényszóró asszisztens',
                'Xenon fényszóró',
            ],
            'Parkolás és kamerák' => [
                '360 fokos kamerarendszer',
                'Első parkolóradar',
                'Első-hátsó parkolóradar',
                'Parkolóradar',
                'Tolatókamera',
                'Tolatókamera bemenet',
                'Tolatóradar',
            ],
            'Ajtók, ablakok és tükrök' => [
                'Centrálzár',
                'Elektromos ablak elöl',
                'Elektromos ablak hátul',
                'Elektromos ablakok',
                'Elektromos csomagtérajtó-mozgatás',
                'Elektromos tükör',
                'Elektromosan behajtható külső tükrök',
                'Automatikusan sötétedő belső tükör',
                'Automatikusan sötétedő külső tükör',
                'Kulcsnélküli indítás',
                'Kulcsnélküli nyitórendszer',
                'Kétoldali tolóajtó',
                'Tolóajtó',
                'Központi zár',
            ],
            'Ülések és elektromos beállítások' => [
                'Elektromos ülésállítás vezetőoldal',
                'Elektromos ülésállítás utasoldalon',
            ],
            'Teljesítmény és menetdinamika' => [
                'ADS (adaptív lengéscsillapító)',
                'Állítható felfüggesztés',
                'Automatikus hengerlekapcsolás',
                'Chiptuning',
                'EDC (elektronikus lengéscsillapítás vezérlés)',
                'Elektronikus futómű hangolás',
                'Elektronikus rögzítőfék',
                'Kerámia féktárcsák',
                'Kormányváltó',
                'Motormegállító rendszer',
                'Sebességfüggő szervókormány',
                'Sportfutómű',
                'Sperr differenciálmű',
                'Szervokormány',
                '4WS - összkerékkormányzás',
            ],
            'Kerekek és gumik' => [
                'Defektjavító készlet',
                'Defekttűrő abroncsok',
                'Könnyűfém felni',
                'Króm felni',
                'Pótkerék',
            ],
            'Tető és napfénytető' => [
                'Napfénytető',
                'Panorámatető',
                'Tolótető - elektromos',
                'Tolótető (napfénytető)',
            ],
            'Vontatás és csomagtér' => [
                'Csomag rögzítő',
                'Faberakás',
                'Pót üzemanyagtartály',
                'Tetőcsomagtartó',
                'Tetőre szerelhető kerékpártartó',
                'Vonóhorog',
                'Vonóhorog - elektromosan kihajtható',
                'Vonóhorog - levehető fejjel',
                'Vonóhorgos kerékpártartó',
                'Bukócső',
            ],
            'Elektromos jármű és töltés' => [
                '230V Csatlakozó hátul',
                'Otthoni hálózati töltő',
                'Type2 töltőkábel',
            ],
            'Head-up display és műszerek' => [
                'Head-up display',
                'HUD / Head-Up Display kiterjesztett valóság funkcióval',
                'Gesztusvezérlés',
            ],
            'Járműtörténet és eladói információk' => [
                'ÁFA visszaigényelhető',
                'Amerikai modell',
                'Autóbeszámítás lehetséges',
                'Azonnal elvihető',
                'Bemutató jármű',
                'Első forgalomba helyezés Magyarországon',
                'Első tulajdonostól',
                'Frissen szervizelt',
                'Garanciális',
                'Garantált km futás',
                'Garázsban tartott',
                'Hölgy tulajdonostól',
                'Jobbkormányos',
                'Keveset futott',
                'Második tulajdonostól',
                'Motorbeszámítás lehetséges',
                'Mozgássérült',
                'Nem dohányzó',
                'Rendelhető',
                'Rendszeresen karbantartott',
                'Taxi',
                'Törzskönyv',
                'Végig vezetett szervizkönyv',
                'Vezetett szervizkönyv',
            ],
            'Sebességtartó rendszerek' => [
                'Tempomat',
                'Távolságtartó tempomat',
            ],
        ];

        foreach ($data as $categoryName => $properties) {
            // Find or create category
            $categoryId = DB::table('property_categories')->where('name', $categoryName)->value('id');
            if (!$categoryId) {
                $categoryId = DB::table('property_categories')->insertGetId([
                    'name' => $categoryName,
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now()
                ]);
            }

            foreach ($properties as $propertyName) {
                // Find or create property
                $propertyId = DB::table('properties')->where('name', $propertyName)->value('id');
                if ($propertyId) {
                    // Update category of existing property
                    DB::table('properties')->where('id', $propertyId)->update([
                        'property_category_id' => $categoryId,
                        'updated_at' => now()
                    ]);
                } else {
                    // Create new property
                    DB::table('properties')->insert([
                        'name' => $propertyName,
                        'property_category_id' => $categoryId,
                        'is_active' => true,
                        'created_at' => now(),
                        'updated_at' => now()
                    ]);
                }
            }
        }
    }
}
